version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    IMAGE_REPO_NAME: tiny-python-app

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo Running tests...
      - pytest

      - echo Logging in to ECR...
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME

      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI

      - COMMIT_ID=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - echo Build started on `date`
      - docker build -t $IMAGE_REPO_NAME:$COMMIT_ID .
      - docker tag $IMAGE_REPO_NAME:$COMMIT_ID $REPOSITORY_URI:$COMMIT_ID

  post_build:
    commands:
      - echo Pushing image...
      - docker push $REPOSITORY_URI:$COMMIT_ID

      # 🔥 Create new task definition with updated image
      - echo Updating ECS task definition...

      - TASK_DEF=$(aws ecs describe-task-definition --task-definition tpapp --query taskDefinition)

      - NEW_TASK_DEF=$(echo $TASK_DEF | jq --arg IMAGE "$REPOSITORY_URI:$COMMIT_ID" '
        .containerDefinitions[0].image = $IMAGE
        | {
            family: .family,
            networkMode: .networkMode,
            executionRoleArn: .executionRoleArn,
            taskRoleArn: .taskRoleArn,
            containerDefinitions: .containerDefinitions,
            requiresCompatibilities: .requiresCompatibilities,
            cpu: .cpu,
            memory: .memory
        }')

      - echo "$NEW_TASK_DEF" > new-task-def.json

      - NEW_TASK_DEF_ARN=$(aws ecs register-task-definition --cli-input-json file://new-task-def.json --query 'taskDefinition.taskDefinitionArn' --output text)

      - echo Deploying new task definition...

      - aws ecs update-service \
          --cluster sriram-test \
          --service tpapp-service-19lzkfsn \
          --task-definition $NEW_TASK_DEF_ARN

artifacts:
  files:
    - '**/*'
