version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    IMAGE_REPO_NAME: tiny-python-app
    TASK_FAMILY: tpapp
    CLUSTER_NAME: tpapp-service-19lzkfsn
    SERVICE_NAME: sriram-test
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
      - yum install -y jq

  pre_build:
    commands:
      - echo Running tests...
      - pytest

      - echo Logging in to ECR...
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME

      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI

      - COMMIT_ID=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $IMAGE_REPO_NAME:$COMMIT_ID .
      - docker tag $IMAGE_REPO_NAME:$COMMIT_ID $REPOSITORY_URI:$COMMIT_ID

  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push $REPOSITORY_URI:$COMMIT_ID
      - echo Creating imagedefinitions.json...
      - printf '[{"name":"tpapp ","imageUri":"%s"}]' $REPOSITORY_URI:$COMMIT_ID > imagedefinitions.json

      - echo "Printing imagedefinitions.json"
      - cat imagedefinitions.json

      # - echo Fetching current task definition...
      # - TASK_DEF=$(aws ecs describe-task-definition --task-definition $TASK_FAMILY --query taskDefinition)

      # - echo Updating image in task definition...
      # - echo "$TASK_DEF" | jq --arg IMAGE "$REPOSITORY_URI:$COMMIT_ID" '.containerDefinitions[0].image = $IMAGE' > new-task-def.json

      # - echo Registering new task definition...
      # - NEW_TASK_DEF_ARN=$(aws ecs register-task-definition --family $TASK_FAMILY --cli-input-json file://new-task-def.json --query 'taskDefinition.taskDefinitionArn' --output text)

      # - echo Updating ECS service...
      # - aws ecs update-service \
      #     --cluster $CLUSTER_NAME \
      #     --service $SERVICE_NAME \
      #     --task-definition $NEW_TASK_DEF_ARN
      # - echo deployment success

# artifacts:
#   files:
#     - '**/*'
artifacts:
  files:
    - imagedefinitions.json
